version: '3.8'

services:
#  api-service:
#    image: api-service
#    container_name: api-service
#    build:
#      context: ./Api
#      dockerfile: Dockerfile
#    ports:
#      - "8080 : 8080"
  
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

networks:
  backend:

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data: